<script lang="ts">
    import { onMount } from "svelte";
    import { Graph, type GraphNode } from "./graph";
    import { RenderedGraph } from "./rendered_graph";

    let canvas: HTMLCanvasElement;

    let innerWidth = window.innerWidth;
    let innerHeight = window.innerHeight;
    let spacePressed = false;
    let mouseHeld = false;

    const reScalaEvents =[
        {"type":"Create","resource":{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109}},
        {"type":"Create","resource":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},"inputs":[{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109},"sink":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119}},
        {"type":"Create","resource":{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39}},
        {"type":"Create","resource":{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43}},
        {"type":"Create","resource":{"idCounter":5,"description":"","enclosing":"todo.TodoAppUI#getContents deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":48}},
        {"type":"Create","resource":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"inputs":[{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39},{"idCounter":5,"description":"","enclosing":"todo.TodoAppUI#getContents deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":48}]},
        {"type":"Discover","source":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Discover","source":{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Discover","source":{"idCounter":5,"description":"","enclosing":"todo.TodoAppUI#getContents deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":48},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Create","resource":{"idCounter":7,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100}},
        {"type":"Create","resource":{"idCounter":8,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"inputs":[{"idCounter":7,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100}]},
        {"type":"Discover","source":{"idCounter":7,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100},"sink":{"idCounter":8,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105}},
        {"type":"Create","resource":{"idCounter":9,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}},
        {"type":"Create","resource":{"idCounter":10,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"inputs":[{"idCounter":8,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105}]},
        {"type":"Discover","source":{"idCounter":8,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"sink":{"idCounter":10,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}},
        {"type":"Create","resource":{"idCounter":11,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"inputs":[{"idCounter":9,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":9,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109},"sink":{"idCounter":11,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}},
        {"type":"Create","resource":{"idCounter":13,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@5) (rescala.scheduler.Levelbased$LevelState@6))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"inputs":[{"idCounter":10,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},{"idCounter":11,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}]},
        {"type":"Discover","source":{"idCounter":10,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"sink":{"idCounter":13,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@5) (rescala.scheduler.Levelbased$LevelState@6))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Discover","source":{"idCounter":11,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"sink":{"idCounter":13,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@5) (rescala.scheduler.Levelbased$LevelState@6))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Create","resource":{"idCounter":14,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112},"inputs":[{"idCounter":13,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@5) (rescala.scheduler.Levelbased$LevelState@6))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}]},
        {"type":"Discover","source":{"idCounter":13,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@5) (rescala.scheduler.Levelbased$LevelState@6))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"sink":{"idCounter":14,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112}},
        {"type":"Create","resource":{"idCounter":15,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114}},
        {"type":"Create","resource":{"idCounter":17,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"inputs":[{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43},{"idCounter":15,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114}]},
        {"type":"Discover","source":{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43},"sink":{"idCounter":17,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Discover","source":{"idCounter":15,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114},"sink":{"idCounter":17,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Create","resource":{"idCounter":18,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118}},
        {"type":"Create","resource":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"inputs":[{"idCounter":17,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},{"idCounter":8,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},{"idCounter":18,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118}]},
        {"type":"Discover","source":{"idCounter":17,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"sink":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Discover","source":{"idCounter":8,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"sink":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Discover","source":{"idCounter":18,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118},"sink":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Create","resource":{"idCounter":20,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34},"inputs":[{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}]},
        {"type":"Discover","source":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":20,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34}},
        {"type":"Create","resource":{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"inputs":[{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}]},
        {"type":"Discover","source":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}},
        {"type":"Value","source":{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":22,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151}},
        {"type":"Create","resource":{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"inputs":[{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153}},
        {"type":"Value","source":{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":24,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153}]},
        {"type":"Discover","source":{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"sink":{"idCounter":24,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":156},"inputs":[{"idCounter":9,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":9,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109},"sink":{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":156}},
        {"type":"Create","resource":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"inputs":[{"idCounter":14,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112}]},
        {"type":"Discover","source":{"idCounter":14,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112},"sink":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}},
        {"type":"Value","source":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"inputs":[{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}},
        {"type":"Value","source":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":28,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"inputs":[{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":21,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":28,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}},
        {"type":"Value","source":{"idCounter":28,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"value":"Value(StringFrag(sup dudes))"},
        {"type":"Create","resource":{"idCounter":29,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"inputs":[{"idCounter":22,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151}]},
        {"type":"Discover","source":{"idCounter":22,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151},"sink":{"idCounter":29,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173}},
        {"type":"Discover","source":{"idCounter":29,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Create","resource":{"idCounter":30,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34},"inputs":[{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}]},
        {"type":"Discover","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"sink":{"idCounter":30,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34}},
        {"type":"Create","resource":{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"inputs":[{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}]},
        {"type":"Discover","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"sink":{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64}},
        {"type":"Value","source":{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"inputs":[{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64}]},
        {"type":"Discover","source":{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"sink":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Discover","source":{"idCounter":19,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Value","source":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":33,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"inputs":[{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64}]},
        {"type":"Discover","source":{"idCounter":31,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"sink":{"idCounter":33,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67}},
        {"type":"Value","source":{"idCounter":33,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":34,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"inputs":[{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":34,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80}},
        {"type":"Value","source":{"idCounter":34,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":35,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"inputs":[{"idCounter":33,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67}]},
        {"type":"Discover","source":{"idCounter":33,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"sink":{"idCounter":35,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57}},
        {"type":"Value","source":{"idCounter":35,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":36,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"inputs":[{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":36,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90}},
        {"type":"Value","source":{"idCounter":36,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":37,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"inputs":[{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":37,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100}},
        {"type":"Value","source":{"idCounter":37,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"value":"Value(<span class=\"todo-count\"><strong>1</strong><span> item left</span></span>)"},
        {"type":"Create","resource":{"idCounter":38,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"inputs":[{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":32,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":38,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103}},
        {"type":"Value","source":{"idCounter":38,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"value":"Value(<button class=\"clear-completed hidden\">remove all done todos</button>)"},
        {"type":"Create","resource":{"idCounter":39,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":34,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80}]},
        {"type":"Discover","source":{"idCounter":34,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"sink":{"idCounter":39,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":40,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}]},
        {"type":"Discover","source":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"sink":{"idCounter":40,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":41,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}]},
        {"type":"Discover","source":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"sink":{"idCounter":41,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":43,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":28,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}]},
        {"type":"Discover","source":{"idCounter":28,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"sink":{"idCounter":43,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},
        {"type":"Create","resource":{"idCounter":44,"description":"","enclosing":"rescala.extra.Tags#RETagListModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":142},"inputs":[{"idCounter":35,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57}]},
        {"type":"Discover","source":{"idCounter":35,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"sink":{"idCounter":44,"description":"","enclosing":"rescala.extra.Tags#RETagListModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":142}},
        {"type":"Create","resource":{"idCounter":45,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":36,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90}]},
        {"type":"Discover","source":{"idCounter":36,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"sink":{"idCounter":45,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":47,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":37,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100}]},
        {"type":"Discover","source":{"idCounter":37,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"sink":{"idCounter":47,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},
        {"type":"Create","resource":{"idCounter":49,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":38,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103}]},
        {"type":"Discover","source":{"idCounter":38,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"sink":{"idCounter":49,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},
    ];

    let graph = new Graph();
    for (let event of reScalaEvents) {
        if (event.type === 'Create') {
            let newNode: GraphNode = {
                id: event.resource.idCounter,
                label: event.resource.enclosing.split('#').at(-1).split(':')[0].split(' ').at(-1).split('.').at(-1),
                value: null
            };
            graph.addNode(newNode);

            if (!event.inputs) continue;

            for (let input of event.inputs) {
                let node = graph.nodes.find(x => x.id === input.idCounter);
                if (node) graph.addEdge(node, newNode);
            }
        } else if (event.type === 'Discover') {
            let n1 = graph.nodes.find(x => x.id === event.source.idCounter);
            let n2 = graph.nodes.find(x => x.id === event.sink.idCounter);
            if (n1 && n2 && !graph.edges.some(x => x[0] === n1 && x[1] === n2)) {
                graph.addEdge(n1, n2);
            }
        } else if (event.type === 'Value') {
            let n = graph.nodes.find(x => x.id === event.source.idCounter);
            n.value = event.value;
        }
    }

    let renderedGraph: RenderedGraph;
    onMount(() => {
        renderedGraph = new RenderedGraph(graph, canvas);

        const render = () => {
            renderedGraph.render();
            requestAnimationFrame(render);
        };
        render();
    });

    const onMouseMove = (e: MouseEvent) => {
        if (!spacePressed || !mouseHeld) return;

        renderedGraph.originX += e.movementX; 
        renderedGraph.originY += e.movementY;
    };

    const onWheel = (e: WheelEvent) => {
        e.preventDefault();

        let scaleChange = Math.pow(1.002, -e.deltaY);

        renderedGraph.originX = (renderedGraph.originX - e.clientX) * scaleChange + e.clientX;
        renderedGraph.originY = (renderedGraph.originY - e.clientY) * scaleChange + e.clientY;
        renderedGraph.scale *= scaleChange;
    };
</script>

<svelte:head>
    <title>REScala Inspector</title>
</svelte:head>

<svelte:window
    bind:innerWidth
    bind:innerHeight
    on:keydown={(e) => e.code === 'Space' && (spacePressed = true)}
    on:keyup={(e) => e.code === 'Space' && (spacePressed = false)}
    on:mousedown={() => mouseHeld = true}
    on:mouseup={() => mouseHeld = false}

    on:keydown={e => e.code === 'KeyI' && renderedGraph.layout.solve(e.shiftKey, 1)}
    on:keydown={e => e.code === 'KeyO'}
    on:keydown={e => e.code === 'KeyP' && renderedGraph.layout.spreadOut()}
    on:keydown={e => e.code === 'KeyD' && renderedGraph.layout.decross()}
    on:keydown={e => e.code === 'KeyB' && (renderedGraph.showNodeBoundingBoxes = !renderedGraph.showNodeBoundingBoxes)}
/>

<canvas
    class="w-full h-full"
    class:cursor-grab={spacePressed}
    class:cursor-grabbing={spacePressed && mouseHeld}
    bind:this={canvas}
    width={innerWidth * window.devicePixelRatio}
    height={innerHeight * window.devicePixelRatio}
    on:mousemove={onMouseMove}
    on:wheel={onWheel}
/>