<script lang="ts">
    import { onMount } from "svelte";
    import type { Writable } from "svelte/store";
    import { fly } from "svelte/transition";
    import { Graph, type GraphNode } from "./graph";
    import type { LayoutNode } from "./graph_layout";
    import { NODE_HEIGHT, RenderedGraph } from "./rendered_graph";
    import type { ReScalaEvent } from "./re_scala";
    import { clamp } from "./utils";
    import Structure from "./Structure.svelte";

    let canvas: HTMLCanvasElement;

    let innerWidth = window.innerWidth;
    let innerHeight = window.innerHeight;
    let spacePressed = false;
    let mouseHeld = false;

    const firstReScalaEvents: ReScalaEvent[] = [
        {"type":"Create","resource":{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109}},
        {"type":"Create","resource":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},"inputs":[{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109},"sink":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119}},
        {"type":"Create","resource":{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39}},
        {"type":"Create","resource":{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43}},
        {"type":"Create","resource":{"idCounter":5,"description":"","enclosing":"todo.TodoAppUI#getContents deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":48}},
        {"type":"Create","resource":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"inputs":[{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39},{"idCounter":5,"description":"","enclosing":"todo.TodoAppUI#getContents deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":48}]},
        {"type":"Discover","source":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Discover","source":{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Discover","source":{"idCounter":5,"description":"","enclosing":"todo.TodoAppUI#getContents deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":48},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Create","resource":{"idCounter":7,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34},"inputs":[{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}]},
        {"type":"Discover","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"sink":{"idCounter":7,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34}},
        {"type":"Create","resource":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"inputs":[{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}]},
        {"type":"Discover","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"sink":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64}},
        {"type":"Value","source":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"inputs":[{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64}]},
        {"type":"Discover","source":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"sink":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Value","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"inputs":[{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64}]},
        {"type":"Discover","source":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"sink":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67}},
        {"type":"Value","source":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"inputs":[{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80}},
        {"type":"Value","source":{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"inputs":[{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67}]},
        {"type":"Discover","source":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"sink":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57}},
        {"type":"Value","source":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"inputs":[{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90}},
        {"type":"Value","source":{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"inputs":[{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100}},
        {"type":"Value","source":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"value":"Value(<span class=\"todo-count\"><strong>0</strong><span> items left</span></span>)"},
        {"type":"Create","resource":{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"inputs":[{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}]},
        {"type":"Discover","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"sink":{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103}},
        {"type":"Value","source":{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"value":"Value(<button class=\"clear-completed hidden\">remove all done todos</button>)"},
        {"type":"Create","resource":{"idCounter":16,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80}]},
        {"type":"Discover","source":{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"sink":{"idCounter":16,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":17,"description":"","enclosing":"rescala.extra.Tags#RETagListModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":142},"inputs":[{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57}]},
        {"type":"Discover","source":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"sink":{"idCounter":17,"description":"","enclosing":"rescala.extra.Tags#RETagListModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":142}},
        {"type":"Create","resource":{"idCounter":18,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90}]},
        {"type":"Discover","source":{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"sink":{"idCounter":18,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":20,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100}]},
        {"type":"Discover","source":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"sink":{"idCounter":20,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},
        {"type":"Create","resource":{"idCounter":22,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103}]},
        {"type":"Discover","source":{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"sink":{"idCounter":22,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},
    ];
    const secondReScalaEvents: ReScalaEvent[] = [
        {"type":"Value","source":{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100}},
        {"type":"Create","resource":{"idCounter":24,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"inputs":[{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100}]},
        {"type":"Discover","source":{"idCounter":23,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100},"sink":{"idCounter":24,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105}},
        {"type":"Create","resource":{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}},
        {"type":"Create","resource":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"inputs":[{"idCounter":24,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105}]},
        {"type":"Discover","source":{"idCounter":24,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"sink":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}},
        {"type":"Create","resource":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"inputs":[{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109},"sink":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}},
        {"type":"Create","resource":{"idCounter":29,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"inputs":[{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}]},
        {"type":"Discover","source":{"idCounter":26,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"sink":{"idCounter":29,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Discover","source":{"idCounter":27,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"sink":{"idCounter":29,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Create","resource":{"idCounter":30,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112},"inputs":[{"idCounter":29,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}]},
        {"type":"Discover","source":{"idCounter":29,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@7) (rescala.scheduler.Levelbased$LevelState@8))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"sink":{"idCounter":30,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112}},
        {"type":"Create","resource":{"idCounter":31,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114}},
        {"type":"Create","resource":{"idCounter":33,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"inputs":[{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43},{"idCounter":31,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114}]},
        {"type":"Discover","source":{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43},"sink":{"idCounter":33,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Discover","source":{"idCounter":31,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114},"sink":{"idCounter":33,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Create","resource":{"idCounter":34,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118}},
        {"type":"Create","resource":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"inputs":[{"idCounter":33,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},{"idCounter":24,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},{"idCounter":34,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118}]},
        {"type":"Discover","source":{"idCounter":33,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"sink":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Discover","source":{"idCounter":24,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"sink":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Discover","source":{"idCounter":34,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118},"sink":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Create","resource":{"idCounter":36,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34},"inputs":[{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}]},
        {"type":"Discover","source":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":36,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34}},
        {"type":"Create","resource":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"inputs":[{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}]},
        {"type":"Discover","source":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}},
        {"type":"Value","source":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":38,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151}},
        {"type":"Create","resource":{"idCounter":39,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"inputs":[{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":39,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153}},
        {"type":"Value","source":{"idCounter":39,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":40,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":39,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153}]},
        {"type":"Discover","source":{"idCounter":39,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"sink":{"idCounter":40,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":41,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":156},"inputs":[{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":25,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109},"sink":{"idCounter":41,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":156}},
        {"type":"Create","resource":{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"inputs":[{"idCounter":30,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112}]},
        {"type":"Discover","source":{"idCounter":30,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112},"sink":{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}},
        {"type":"Value","source":{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"inputs":[{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}},
        {"type":"Value","source":{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"inputs":[{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}},
        {"type":"Value","source":{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"value":"Value(StringFrag(Hello!))"},
        {"type":"Create","resource":{"idCounter":45,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"inputs":[{"idCounter":38,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151}]},
        {"type":"Discover","source":{"idCounter":38,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151},"sink":{"idCounter":45,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173}},
        {"type":"Discover","source":{"idCounter":45,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Value","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"value":"<some html>"},
        {"type":"Discover","source":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Value","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"value":"Value(<span class=\"todo-count\"><strong>1</strong><span> item left</span></span>)"},
        {"type":"Value","source":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":46,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}]},
        {"type":"Discover","source":{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"sink":{"idCounter":46,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":47,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}]},
        {"type":"Discover","source":{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"sink":{"idCounter":47,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":49,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}]},
        {"type":"Discover","source":{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"sink":{"idCounter":49,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},

    ];
    const thirdReScalaEvents: ReScalaEvent[] = [
        {"type":"Value","source":{"idCounter":1,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handler","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":109},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":2,"description":"","enclosing":"todo.TodoAppUI#inputFieldHandler handlerEvent","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":119},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":50,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100}},
        {"type":"Create","resource":{"idCounter":51,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"inputs":[{"idCounter":50,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100}]},
        {"type":"Discover","source":{"idCounter":50,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittext","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":100},"sink":{"idCounter":51,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105}},
        {"type":"Create","resource":{"idCounter":52,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}},
        {"type":"Create","resource":{"idCounter":53,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"inputs":[{"idCounter":51,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105}]},
        {"type":"Discover","source":{"idCounter":51,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"sink":{"idCounter":53,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}},
        {"type":"Create","resource":{"idCounter":54,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"inputs":[{"idCounter":52,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":52,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109},"sink":{"idCounter":54,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}},
        {"type":"Create","resource":{"idCounter":56,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@18) (rescala.scheduler.Levelbased$LevelState@19))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"inputs":[{"idCounter":53,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},{"idCounter":54,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111}]},
        {"type":"Discover","source":{"idCounter":53,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"sink":{"idCounter":56,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@18) (rescala.scheduler.Levelbased$LevelState@19))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Discover","source":{"idCounter":54,"description":"","enclosing":"todo.TaskReferences#createTaskRef changeEditing","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":111},"sink":{"idCounter":56,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@18) (rescala.scheduler.Levelbased$LevelState@19))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Create","resource":{"idCounter":57,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112},"inputs":[{"idCounter":56,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@18) (rescala.scheduler.Levelbased$LevelState@19))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}]},
        {"type":"Discover","source":{"idCounter":56,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@18) (rescala.scheduler.Levelbased$LevelState@19))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"sink":{"idCounter":57,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112}},
        {"type":"Create","resource":{"idCounter":58,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114}},
        {"type":"Create","resource":{"idCounter":60,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@1a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"inputs":[{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43},{"idCounter":58,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114}]},
        {"type":"Discover","source":{"idCounter":4,"description":"","enclosing":"todo.TodoAppUI#getContents toggleAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":43},"sink":{"idCounter":60,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@1a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Discover","source":{"idCounter":58,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114},"sink":{"idCounter":60,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@1a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125}},
        {"type":"Create","resource":{"idCounter":61,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118}},
        {"type":"Create","resource":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"inputs":[{"idCounter":60,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@1a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},{"idCounter":51,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},{"idCounter":61,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118}]},
        {"type":"Discover","source":{"idCounter":60,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@1a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"sink":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Discover","source":{"idCounter":51,"description":"","enclosing":"todo.TaskReferences#createTaskRef edittextStr","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":105},"sink":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Discover","source":{"idCounter":61,"description":"","enclosing":"todo.TaskReferences#createTaskRef deltaEvt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":118},"sink":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}},
        {"type":"Create","resource":{"idCounter":63,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34},"inputs":[{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}]},
        {"type":"Discover","source":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":63,"description":"","enclosing":"todo.Storing.storedAs","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/Storing.scala","line":34}},
        {"type":"Create","resource":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"inputs":[{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142}]},
        {"type":"Discover","source":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}},
        {"type":"Value","source":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":65,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151}},
        {"type":"Create","resource":{"idCounter":66,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"inputs":[{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":66,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153}},
        {"type":"Value","source":{"idCounter":66,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":67,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":66,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153}]},
        {"type":"Discover","source":{"idCounter":66,"description":"","enclosing":"todo.TaskReferences#createTaskRef editInput","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":153},"sink":{"idCounter":67,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":68,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":156},"inputs":[{"idCounter":52,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109}]},
        {"type":"Discover","source":{"idCounter":52,"description":"","enclosing":"todo.TaskReferences#createTaskRef editDiv","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":109},"sink":{"idCounter":68,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":156}},
        {"type":"Create","resource":{"idCounter":69,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"inputs":[{"idCounter":57,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112}]},
        {"type":"Discover","source":{"idCounter":57,"description":"","enclosing":"todo.TaskReferences#createTaskRef editingV","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":112},"sink":{"idCounter":69,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}},
        {"type":"Value","source":{"idCounter":69,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":70,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"inputs":[{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":70,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}},
        {"type":"Value","source":{"idCounter":70,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":71,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"inputs":[{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148}]},
        {"type":"Discover","source":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"sink":{"idCounter":71,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}},
        {"type":"Value","source":{"idCounter":71,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"value":"Value(StringFrag(World!))"},
        {"type":"Create","resource":{"idCounter":72,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"inputs":[{"idCounter":65,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151}]},
        {"type":"Discover","source":{"idCounter":65,"description":"","enclosing":"todo.TaskReferences#createTaskRef removeButton","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":151},"sink":{"idCounter":72,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173}},
        {"type":"Discover","source":{"idCounter":72,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Value","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"value":"<some html>"},
        {"type":"Discover","source":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Value","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"value":"Value(<span class=\"todo-count\"><strong>2</strong><span> items left</span></span>)"},
        {"type":"Value","source":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"value":"<some html>"},
        {"type":"Create","resource":{"idCounter":73,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":69,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}]},
        {"type":"Discover","source":{"idCounter":69,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"sink":{"idCounter":73,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":74,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":70,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}]},
        {"type":"Discover","source":{"idCounter":70,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"sink":{"idCounter":74,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":76,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":71,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}]},
        {"type":"Discover","source":{"idCounter":71,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"sink":{"idCounter":76,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},
        {"type":"Create","resource":{"idCounter":77,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159}]},
        {"type":"Discover","source":{"idCounter":42,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":159},"sink":{"idCounter":77,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":78,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159},"inputs":[{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165}]},
        {"type":"Discover","source":{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"sink":{"idCounter":78,"description":"","enclosing":"rescala.extra.Tags#genericReactiveAttrValue $anon#apply","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":159}},
        {"type":"Create","resource":{"idCounter":80,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85},"inputs":[{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167}]},
        {"type":"Discover","source":{"idCounter":44,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":167},"sink":{"idCounter":80,"description":"","enclosing":"rescala.extra.Tags#REFragModifier#applyTo","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":85}},

    ];
    const fourthReScalaEvents: ReScalaEvent[] = [
        {"type":"Value","source":{"idCounter":58,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":60,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@1a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":64,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":70,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"value":"Value(<span class=\"todo-count\"><strong>1</strong><span> item left</span></span>)"},
        {"type":"Value","source":{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"value":"Value(<button class=\"clear-completed\">remove all done todos</button>)"},
    ]
    const fifthReScalaEvents: ReScalaEvent[] = [
        {"type":"Value","source":{"idCounter":31,"description":"","enclosing":"todo.TaskReferences#createTaskRef doneClick","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":114},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":33,"description":"»«'(or (rescala.scheduler.Levelbased$LevelState@9) (rescala.scheduler.Levelbased$LevelState@a))","enclosing":"rescala.operator.EventBundle#Event#||","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/shared/src/main/scala/rescala/operator/Event.scala","line":125},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":37,"description":"","enclosing":"todo.TaskReferences#createTaskRef taskData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":148},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":43,"description":"","enclosing":"todo.TaskReferences#createTaskRef listItem","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":165},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":14,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":100},"value":"Value(<span class=\"todo-count\"><strong>0</strong><span> items left</span></span>)"},
    ];
    const sixthReScalaEvents: ReScalaEvent[] = [
        {"type":"Value","source":{"idCounter":3,"description":"","enclosing":"todo.TodoAppUI#getContents removeAll","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":39},"value":"<some html>"},
        {"type":"Drop","source":{"idCounter":72,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Drop","source":{"idCounter":45,"description":"","enclosing":"todo.TaskReferences#createTaskRef","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":173},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Discover","source":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Discover","source":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59}},
        {"type":"Value","source":{"idCounter":6,"description":"","enclosing":"todo.TodoAppUI#getContents tasksRDT","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":59},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":8,"description":"","enclosing":"todo.TodoAppUI#getContents tasksList","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":64},"value":"<some html>"},
        {"type":"Drop","source":{"idCounter":62,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Drop","source":{"idCounter":35,"description":"","enclosing":"todo.TaskReferences#createTaskRef crdt","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TaskData.scala","line":142},"sink":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66}},
        {"type":"Value","source":{"idCounter":9,"description":"","enclosing":"todo.TodoAppUI#getContents tasksData","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":66},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":10,"description":"","enclosing":"todo.TodoAppUI#getContents taskTags","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":67},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":11,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":80},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":13,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":90},"value":"<some html>"},
        {"type":"Value","source":{"idCounter":15,"description":"","enclosing":"todo.TodoAppUI#getContents","file":"/Users/davidpayr/git/private/REScala/Modules/Example Todolist/src/main/scala/todo/TodoAppUI.scala","line":103},"value":"Value(<button class=\"clear-completed hidden\">remove all done todos</button>)"},
        {"type":"Value","source":{"idCounter":12,"description":"","enclosing":"rescala.extra.Tags#SignalTagListToScalatags#asModifierL","file":"/Users/davidpayr/git/private/REScala/Modules/Reactives/js/src/main/scala/rescala/extra/Tags.scala","line":57},"value":"<some html>"},
    ]

    const eventGroups = [firstReScalaEvents, secondReScalaEvents, thirdReScalaEvents, fourthReScalaEvents, fifthReScalaEvents, sixthReScalaEvents];

    let graph = new Graph();
    //graph.processReScalaEvents(eventGroups[0]);
    
    //let n1: GraphNode = { id: 0, label: '', value: null };
    //let n2: GraphNode = { id: 1, label: '', value: null };
    //let n3: GraphNode = { id: 2, label: '', value: null };
    //graph.addNode(n1);
    //graph.addNode(n3);
    //graph.addEdge(n1, n3);
    
    

    let i = 1;
    const loadNextEvents = () => {
        /*
        let edge = graph.edges.find(x => x[0] === n1 && x[1] === n2);
        if (edge) {
            graph.removeEdge(edge);
            return;
        }

        graph.addNode(n2);
        graph.addEdge(n1, n2);
        graph.addEdge(n2, n3);
        
        return;
        */
        
        //graph.processReScalaEvents(eventGroups[i++]);
    };

    let renderedGraph: RenderedGraph;
    let hoveredNode: Writable<LayoutNode>;
    onMount(() => {
        renderedGraph = new RenderedGraph(graph, canvas);
        hoveredNode = renderedGraph.hoveredNode;

        const render = () => {
            renderedGraph.render();
            requestAnimationFrame(render);
        };
        render();

        let eventsProcessed = 0;
        let lastId: number = null;

        if (typeof chrome !== 'undefined') {
            const handle = (result: { events: ReScalaEvent[], id: number }, isException: any) => {
                if (isException) {
                    console.log("exception", isException);
                    return;
                }

                if (lastId && lastId !== result.id) {
                    eventsProcessed = 0;
                    graph = new Graph();
                    renderedGraph = new RenderedGraph(graph, canvas);
                    hoveredNode = renderedGraph.hoveredNode;
                }
                lastId = result.id;

                graph.processReScalaEvents(result.events.slice(eventsProcessed));
                eventsProcessed = result.events.length;
            };

            const getData = () => {
                let events = (window as any).reScalaEvents as ReScalaEvent[];

                return {
                    id: (window as any).reScalaId as number,
                    events
                };
            };
            setInterval(() => {
                chrome.devtools.inspectedWindow.eval(`(${getData.toString()})()`, handle);
            }, 1000/30);
        }
    });

    const onMouseMove = (e: MouseEvent) => {
        renderedGraph.supplyMousePosition({ x: e.clientX, y: e.clientY });

        if (!spacePressed || !mouseHeld) return;

        renderedGraph.originX += e.movementX; 
        renderedGraph.originY += e.movementY;
    };

    const onWheel = (e: WheelEvent) => {
        e.preventDefault();

        let scaleChange = Math.pow(1.002, -e.deltaY);

        renderedGraph.originX = (renderedGraph.originX - e.clientX) * scaleChange + e.clientX;
        renderedGraph.originY = (renderedGraph.originY - e.clientY) * scaleChange + e.clientY;
        renderedGraph.scale *= scaleChange;
    };

    $: popupStyle = (() => {
        if (!$hoveredNode) return;

        let width = 208;
        let height = 150;
        let left = clamp($hoveredNode.visualCenter().x * renderedGraph.scale + renderedGraph.originX - width/2, 10, window.innerWidth - width - 10);
        let top = $hoveredNode.visualPosition().y * renderedGraph.scale + renderedGraph.originY - height;
        let paddingTop = 0;
        let paddingBottom = 10;

        if (top < 10) {
            top += height + NODE_HEIGHT * renderedGraph.scale;
            [paddingTop, paddingBottom] = [paddingBottom, paddingTop];
        }

        return {
            width,
            height,
            left,
            top,
            paddingTop,
            paddingBottom
        };
    })();
</script>

<svelte:head>
    <title>REScala Inspector</title>
</svelte:head>

<svelte:window
    bind:innerWidth
    bind:innerHeight
    on:keydown={(e) => e.code === 'Space' && (spacePressed = true)}
    on:keyup={(e) => e.code === 'Space' && (spacePressed = false)}
    on:mousedown={() => mouseHeld = true}
    on:mouseup={() => mouseHeld = false}

    on:keydown={e => e.code === 'KeyI' && renderedGraph.layout.solve(e.shiftKey, 1)}
    on:keydown={e => e.code === 'KeyO'}
    on:keydown={e => e.code === 'KeyP' && renderedGraph.layout.spreadOut()}
    on:keydown={e => e.code === 'KeyD' && renderedGraph.layout.decross()}
    on:keydown={e => e.code === 'KeyB' && (renderedGraph.showNodeBoundingBoxes = !renderedGraph.showNodeBoundingBoxes)}
    on:keydown={e => e.code === 'KeyN' && loadNextEvents()}
/>

<canvas
    class="w-full h-full"
    class:cursor-grab={spacePressed}
    class:cursor-grabbing={spacePressed && mouseHeld}
    bind:this={canvas}
    width={innerWidth * window.devicePixelRatio}
    height={innerHeight * window.devicePixelRatio}
    on:mousemove={onMouseMove}
    on:wheel={onWheel}
/>

{#if $hoveredNode}
    <div
        transition:fly={{y: -10, duration: 150}}
        class="absolute text-xs"
        style:width={popupStyle.width + 'px'}
        style:height={popupStyle.height + 'px'}
        style:left={popupStyle.left + 'px'}
        style:top={popupStyle.top + 'px'}
        style:padding-top={popupStyle.paddingTop + 'px'}
        style:padding-bottom={popupStyle.paddingBottom + 'px'}
    >
        <div class="w-full h-full bg-zinc-700 shadow rounded-md p-2 px-3 space-y-3">
            <p class="opacity-30 text-[10px] break-words">
                {@html '/' + $hoveredNode.node.reScalaResource.path.slice(0, -1).join('/').replaceAll('/', '/<wbr>')}
            </p>
            <div class="flex w-full !mt-1">
                <p class="truncate flex-1">
                    <span class="opacity-50 font-bold uppercase text-[11px]">Label</span><br>
                    {$hoveredNode.node.label}
                </p>
                <p class="truncate text-right">
                    <span class="opacity-50 font-bold uppercase text-[11px]">ID</span><br>
                    {$hoveredNode.node.id}
                </p>
            </div>
            <p class="truncate">
                <span class="opacity-50 font-bold uppercase text-[11px]">Value</span><br>
                {$hoveredNode.node.value}
            </p>
        </div>
    </div>
{/if}

{#if renderedGraph}
    <Structure graphLayout={renderedGraph.layout} />
{/if}